### ISSUE TITLE
build "fat" base image

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#1002]
The same base image is used for local development, building (CI) and also deploying. For this reason our image includes please_cli and all of the tools needed for deployment.

Estimate is that "fat"  image will be around 4-5GB. Maybe we can shave off some size if we flatten the image.

Before we start working on this, we would need to solve #965 first.

## Pros

- It would be much nicer first time experience for developers if they wouldn't have to download "the world" before they start the development.
- even build images might benefit something in terms of performance once docker images are caches in taskcluster worker.
- we could use this image to bootstrap development via [Janitor](https://janitor.technology/)

## Cons

- Base image is bigger and bigger image means and it will take long to build base image. even currently it takes 1h.
- Some contributors might be behind slow connections and having to download 4GB every second week might be too disruptive.

**Comment by garbas** [comment]
@rail @mozbhearsum you have more experience with contributors? would having a bigger docker image (eg ~4GB) be a problem for contributors? 

@marco-c @La0 now that we will be all using docker for development, you think having a bigger image would slow you down too much? I assume we all have good enough connections that downloading a 4G every 2 weeks would be ok. it is not ideal but a compromise.

@jankeromnes I still haven't give up on having a button at https://docs.mozilla-releng.net to start development in seconds :) is it possible to run containers in janitor in privileged mode?

I suppose we can try and see but maybe collecting some feedback before would make sense.

**Comment by mozbhearsum** [comment]
It's really tough to say how much size makes a difference. Balrog uses two different Docker images that total to a bit over 300MB. I'm not sure if there's a huge difference between 300MB and 4GB for users with slow connections or limits to how much they can download. Smaller is certainly better for everyone though.

Another thing to look at is to ensure you're caching as much as possible. For example, I discovered that Balrog wasn't properly caching python dependencies during test runs, so each test run would re-download everything from requirements.txt. That was something that people actively complained about.

**Comment by jankeromnes** [comment]
> @jankeromnes I still haven't give up on having a button at https://docs.mozilla-releng.net to start development in seconds :) is it possible to run containers in janitor in privileged mode?

That's super cool to read! 😄 Thanks for making my day! 🎉 

However, Janitor containers don't run in privileged mode, because that's essentially giving root access on the shared Docker server to any user (which is scary). Is it possible to make an unprivileged releng-services environment that's still useful for development?

Note that we've identified a few developer use cases that require extra privileges (see https://github.com/JanitorTechnology/janitor/issues/232), and we're currently investigating to support them (ideally, we could just enable a few low-risk Docker capabilities, but if some required features are just too risky, we might have to selectively bump some container privileges, and thus consider their owners as root on our servers).

**Comment by rail** [comment]
I wonder if we can generate multiple base images instead of having one monolith. I guess that increasing the image size won't help newcomers, especially if they would need to re-download the whole thing every 2 weeks.

**Comment by jankeromnes** [comment]
Random note: Large monolithic Docker images aren't a problem for Janitor; they're actually preferred (since we have one image per project, and many developers creating many containers from this image, copy-on-write makes it more interesting to pre-install a 5 MB tool into the single base image than having `X` developers install it into their `Y` containers separately). The larger the Janitor image, the more we save on developer time and disk space (and transferring a ** GB image every week is nothing on our dedicated servers' gigabit bandwidth).

**Comment by marco-c** [comment]
I think forcing the download of ~4 GB every two weeks might be a bit too much. When I'm not in the office, my download speed is 1 MB/s or worse. Downloading 4 GB means more than 1 hour spent waiting. If we are traveling and in a hotel with a bad connection, it would be even worse.

**Comment by garbas** [comment]
@mozbhearsum tnx for the info. I need to check out the size of our current image and then make sure we have something as small as balrog.

@rail we can not have per project base images. since in that please bash script we don't know which projects are we going to work on and i don't really want to parse cli arguments in bash.

@jankeromnes I suppose we can have large docker image only for those who want to use it and also to use it with janitor. I haven't look at exact capabilities that Nix needs for sandbox, but I can look it up.

@marco-c makes sense. i think we should build "fat" image alongside our minimal image and use it with janitor. i think that would make contributions to services even easier.
