### ISSUE TITLE
automatic dependency updates for projects

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla/release-services#1084]
We need to provide an automated way of updating dependencies for projects on nightly basis. 

There already is an update-dependencies command, `./please tools update-dependencies <project>`, to update dependencies for a given project. 

Also there is already a way to also deploy (alongside other deployments of a project) a taskcluster hook which would run on a nightly basis. We should configure such deployment target for each project.

In case of python projects (pypi2nix) we should also upload wheels to https://cache.mozilla-releng.net/wheels S3 bucket.

We need to extend update-dependencies command to be also able to commit changes and force push changed to `updates-<project>` branch. This functionality should be hidden behind `--push-to-branch` option.

<details>
 <summary>Old description by @mozbhearsum </summary>
According to our newly written Python standards, "Projects should have a mechanism in place to monitor for new upstream dependencies, and run automated tests against the updated dependencies. E.g. https://pyup.io/".

My understanding of the current state of things is that a human needs to remember to update nixpkgs in order to get Python dependencies upgraded, eg: #886. Pyup probably doesn't work for services, because of Nix, but it will need some other solution to this problem to comply with the standards.
</details>

**Comment by garbas** [comment]
@mozbhearsum As you suggested I'm bringing @catlee into this discussion.

I'm sorry for being pain in the ass (yet again), but I think I have few points about the pyup.io requirement. As python standards document was finalizing I didn't want to bring this up for two reasons: (1) didn't want to kill the energy and the effort going into that document at that moment, especially since (2) I didn't have time to defend my arguments due to work and parental leave.

My rationale:

1. The moment a project gets dependencies updated we can consider it to be out of date. I assume here we don't want to redeploy immediately once new version of one dependency is available, but we want to batch this and wait (a week or two or three) and redeploy multiple version bumps.

2. Because we consider project to be out of date all the time, a service like pyup.io does not bring any value. This is because we would never blindly merge a PR create by pyup.io. We would require (I hope) somebody to look what we are updating, testing in staging that everything still works for a period of time. And this is a manual and tedious process.

3. In `mozilla-releng/services` we have a policy to update the dependencies right after the deployment to production. That means we can test version bumps in staging for 1-2 weeks.

4. Since a manual process is anyway needed, we rather make this a policy of the bi-weekly deployment then recurring task. A bi-weekly deployment is a burden that we should all share.

5. I think goal should be to merge version bumps directly into master on a daily basis. Because we are using Python achieving this is even harder then with any of the statically typed languages, but not impossible. While project is being in the development stage of its life there is no need to automate the dependency updates, but we should be working towards more resilient python code.
 - testing calls to other libraries (integration tests)
 - >90% code coverage
 - extensive use of typing
 - have smoke test and run them also for staging
Outcome of each update accident should be additional test that would catch similar issues in the future.
As project moves into maintenance part of its life we can then at one point - once we decide that the code is of good quality - enable merging version bumps directly into master.

6. Using pyup.io wont solve the problem, having "recurring maintenance of our services" being part of our work sound more like a solution to me. I assume here that everybody on the team should be able to do it, just like build duty. Having a process like these would also fix the problem where only certain people can (re)deploy certain projects.

Again I'm sorry for always trying to "piss against the wind" (I'm not sure the same expression is used in English), but I would like to solve this problem and not just ignore PRs created by pyup.io.

**Comment by catlee** [comment]
The standards are written for our python projects in general, and not specifically for releng-services. The particular problem that pyup is solving in general is project dependencies drifting months or years out of date without notice.

The value of automated pull requests and testing of dependency upgrades is that it provides the team with notification that something upstream has changed, and whether it breaks any of the automated tests. We can then make a decision about whether the change warrants an immediate release, or if it can wait for the next scheduled deploy. You're right that this doesn't completely solve the issue, since test coverage may be incomplete for various reasons, and deployments always need to be tested. Striving for increased code coverage and using typing can help, but they aren't silver bullets, and are also out of scope for this issue.

The point remains that we need automated notification and testing of upstream dependency changes so that we can make informed decisions about which ones to accept, and when.

**Comment by garbas** [comment]
ok this is how i understand this: we need to implement this automatic thingy just to follow the standards, even though we will ignore those PRs since we are already doing this as part of the bi-weekly deployment / maintenance, but they will serve as notification for people not working with/on m-r/services.

if nothing urgent comes up in Q3 i think this will be a good task to start the quarter. /cc @lundjordan

**Comment by mozbhearsum** [comment]
I'm not sure why this has to be something that's ignored. Once you have a thing that's checking for updated deps and opening PRs for them (which doesn't have to be pyup.io), presumably tests are being run, so you should have some confidence in their mergability? Or do humans go around and do extensive testing of each service before taking such upgrades? If they do, could they use the PR as a basis for the testing instead of doing the upgrades themselves?

**Comment by mozbhearsum** [comment]
To be clear: the policy isn't asking for automatic updating of master, it's asking for automatic opening of PRs. Most of other projects also have branch protection enabled for the master branch, so PRs are required (and desired) for these sorts of changes.

**Comment by lundjordan** [comment]
> ok this is how i understand this: we need to implement this automatic thingy just to follow the standards

This is not a fair statement. Gentle reminder that there are humans behind the these standards who spent time and mindfulness in its creation.

@garbas  - I agree with a few things you mentioned. Getting off relengapi is top priority. Services has proven thus far that the owners of releng/services are diligent about keeping their packages up to date. I believe that is reason enough to delay this ticket until relengapi migration is complete (next month)

Saying that, this ticket and the standards behind them hold value. Keeping packages up to date is a conscious effort as of now. People are lazy, machines are not.  Also, the ones who are keeping on top of things today may not be here tomorrow. To comply, we do not need to use specifically with pyup.io. There is flexibility. However, we **should** have something fulfilling its role in services: checking for updates automatically so that that **check** is not left to the weekly decision of people.

You mentioned this would be good to start in Q3 with other python upgrade efforts and we should discuss it in our meeting in SF. Both sound reasonable to me. 👍

**Comment by garbas** [comment]
@mozbhearsum i took over the description of this ticket to provide more details what needs to be done.
