### ISSUE TITLE
Change user-agent in mozdata.ini for shipit-bot-uplift

### ISSUE THREAD

**Issue by calixteman** [mozilla/release-services#1286]
In order to make easier the identification of the tool which uses libmozdata, please update the user agent.

**Comment by rv404674** [comment]
Hi @calixteman , can i take up this issue.

**Comment by kevinluvian** [comment]
Hi @calixteman @La0 
I added the mozdata.ini at this PR: https://github.com/mozilla/release-services/pull/1711
kindly review it to make sure that it is correct.

it seems uplift/bot is replacing the TOKEN manually:
https://github.com/mozilla/release-services/blob/bd3823b22243eb577300a8458e85a6dc75db10da/src/uplift/bot/uplift_bot/bugzilla.py#L39
so I didn't put it inside the mozdata.ini because from what I read in libmozdata repo, if the key is not inside mozdata.ini it will use the default value, so this patch should be backward compatible
