### ISSUE TITLE
Silent should be optional, not a default

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1320]
In most cases, we are failing to show proper error messages. This is a pain for new developers.
I think we should make the please commands not silent by default.

**Comment by garbas** [comment]
In beginning this year when I implemented I actually received the opposite feedback, which I collected at Austin All Hands. 

I do agree that suppressing error messages is not good, but I do think running in silent mode is better since it doesn't "scare" newcomers.

That said I think we can do both. Run in silent mode and in case of error print error. @marco-c would this suggestion work for you?

/me assumes this implies to `./please` bash script

**Comment by marco-c** [comment]
Sounds good to me, even though we've had at least one case where there was an error that we didn't detect (https://github.com/mozilla/release-services/issues/1319). In that case, it would have been painful to debug for a newcomer even if we printed output on error.

I prefer not silent by default, but if you received opposite feedback from many people, I guess it's better to follow that feedback.

**Comment by marco-c** [comment]
Hit by this again, @ReapOmen had to spend time for debugging a stupid thing.
