### ISSUE TITLE
Cleanup Sentry backlog

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#1553]

**Comment by garbas** [comment]
@marco-c how would we change the process so that we would keep an eye on sentry backlog and keep it more or less clean? that way once we clean it we also have a way how to keep it clean?

should we make it part of the post deployment steps every 2 weeks? eg. on Friday after production deployment every owner of project would need to go over sentry alerts for their project?

 do you have any other ideas?

**Comment by marco-c** [comment]
> should we make it part of the post deployment steps every 2 weeks? eg. on Friday after production deployment every owner of project would need to go over sentry alerts for their project?

The only drawback with this idea is that basically we will look at the issues of a given deployment on the following deployment.
Maybe we should look at the issues a couple of days after the deployment, setting some calendar reminders to do so.
