### ISSUE TITLE
Problem with an automated review: readability-implicit-bool-conversion

### ISSUE THREAD

**Issue by smaug----** [mozilla/release-services#1622]
**Phabricator URL:** https://phabricator.services.mozilla.com/D8888

**Problem:** …
Warning: Implicit conversion 'nsIDocument *' -> bool [clang-tidy: readability-implicit-bool-conversion]

if (doc && XULBroadcastManager::MayNeedListener(*this)) {
    ^~~
    ( != nullptr)

readability-implicit-bool-conversion seems to be totally opposite of Mozilla coding style.
One must not do doc != nullptr per coding style.

**Comment by marco-c** [comment]
This should be fixed soon, see #1585.

@abpostelnicu could you confirm it is fixed?

**Comment by abpostelnicu** [comment]
The problem here is that this revision is created on top of a m-c where the configuration for `readability-implicit-bool-conversion` is not present so when we are doing the analysis we don't actually use [these flags](https://searchfox.org/mozilla-central/source/tools/clang-tidy/config.yaml#118).
Re-basing this to the latest m-c solves the issue.
