### ISSUE TITLE
treestatus/update should show the current Reason and MOTD for trees being updated

### ISSUE THREAD

**Issue by philor** [mozilla/release-services#163]
With the current treestatus, if you want to edit the Reason or MOTD for a tree, you can either do it from https://api.pub.build.mozilla.org/treestatus/details/fx-team where you can copy-paste-edit both or from https://api.pub.build.mozilla.org/treestatus/ where you can copy-paste-edit Reason.

With https://mozilla-releng.net/treestatus/show/fx-team you can in fact copy one, go to /update, paste-edit, go to / and then to /show/fx-team to copy the other and when you go back to /update your edit of the first one is still present, but the fact that doing so works is more surprising UI than normal expected UI.

Sadly, with affected trees listed above, rather than beside, the UI for updating, it's entirely possible that once I actually see the current Reason and MOTD listed while closing every tree and have to scroll to even see the changing UI, I'll complain about that too.

**Comment by garbas** [comment]
@philor Thank you a lot for quick response. I really really appreciated it. I've fixed all of them (https://github.com/mozilla-releng/services/pull/167) except I have some questions how we can best solve this.

If I understand the use case it is that in some cases you would need to copy-paste reason from currently selected trees that you are editing.

I can think of 2 options how to solve this:
- two column like in current TreeStatus, which I don't think is a good way since the UI doesn't scale to mobile. of course i can use any of the responsive grids but having
- a second option (which i would prefer) is to show reasons of selected trees above the form where it currently says "You are about to update the following trees:". probably initially only showing the number with "expand" button which would show more details about the selected trees.

If you think it would be better to do a quick chat since I am not that skilled with expressing design in works I am all for it. Especially with UI/UX a quick chat can be more productive.

**Comment by philor** [comment]
Right, there are three primary use cases for treestatus:

1. It's a scheduled Tree Closing Window, or some part of the infra is broken, and I need to close everything at once, all with the same reason.
2. Something happened, usually a bad push, and I need to close one tree.
3. Either because I didn't yet know details (closed in a panic, then filed the bug, or discovered that there were five sorts of bustage rather than just the three I initially though) or because the first message was inadequate or had a typo, I need to edit the reason (or, much more rarely, the MOTD)

For the first two, I don't care at all about any existing reason, and in both cases I very much want the UI to get out of my way and let me get to closing (it's not uncommon to be closing because the bustage means that every single push is going to require starring several hundred failed jobs, so letting a couple more pushes in while you are closing is painful), and only in the third do I need to at least see, and better yet be able to copy, the existing message.

Because the first two are both more common and more urgent than the third, I'm not excited about

You are about to update the following trees:
* ash
  Reason:
  MOTD:
* autoland
  Reason:
  MOTD:
...
* comm-aurora-seamonkey
  Reason:
  MOTD: MOTDs are a nice thing we can't have
...
...

above the changing UI. My first thought was to move the list below the UI, but I think that's a bad idea: in the current treestatus I'm prone to accidentally changing more trees than I realize I had selected, and that seems even more likely with them listed below the only part of the page I'm interested in looking at. Probably given how rarely the third use case actually comes up, something like

+ ash
+ autoland
- cedar
  Reason:
  MOTD:
+ comm-aurora-seamonkey

would meet the rare need to copy-paste. If that's easy enough to do with your toolkit, call it a good-first-bug and let it wait for a contributor, it's pretty low priority.

(One other option that is probably completely unworkable: the treestatus before the current treestatus put the existing reason/motd into the textbox, on the assumption that you would be editing more often than you would be starting fresh. My memory is almost completely gone, so I can't say what it did for multiple trees.)

**Comment by philor** [comment]
Thanks, Markdown, that final list was actually supposed to have a "-" in front of cedar, and a "+" in front of the other three tree names.
