### ISSUE TITLE
Make the clang-format fix patch links open in the browser

### ISSUE THREAD

**Issue by ehsan** [mozilla/release-services#1690]
**Phabricator URL:** https://phabricator.services.mozilla.com/D12430#306487f

**Problem:** It would be nice for the user to be able to see the generated patch when clicking on links such as https://queue.taskcluster.net/v1/task/WIxiWanPQgitQdhvMOHseA/runs/0/artifacts/public/results/clang-format-PHID-DIFF-ykspmg4mhdehw4stcdos.diff instead of having to download a file.  If there is an option of enabling viewing these links in the browser, that would be a very welcome tweak.

**Comment by La0** [comment]
Hello @ehsan ,

We've tried to do that, the options we've though of:

 - display directly the patch content in the bot's comment (would not work well for multiple issues)
 - make a commit with the clang-format fixes so the dev can cherry-pick it if wanted (would be tricky with user access)
 - make a webextension displaying the content of such a patch
 - add a link to the patch (as of right now)

Work on n°2 (new commit) is in my pipeline. I'll keep you posted

**Comment by jankeromnes** [comment]
@ehsan great suggestion, thanks! I agree that having to download & open in editor just to see the patch is a little annoying.

@La0 do you know if there is a way to change the ContentType of Taskcluster artifacts? (e.g. using something like "text/plain"). I can see in the Task's [artifacts](https://tools.taskcluster.net/groups/WIxiWanPQgitQdhvMOHseA/tasks/WIxiWanPQgitQdhvMOHseA/runs/0/artifacts) that any [*.txt file](https://queue.taskcluster.net/v1/task/WIxiWanPQgitQdhvMOHseA/runs/0/artifacts/public/results/PHID-DIFF-ykspmg4mhdehw4stcdos-mozlint.txt) will open directly in the browser (new tab), while the [*.diff file](https://queue.taskcluster.net/v1/task/WIxiWanPQgitQdhvMOHseA/runs/0/artifacts/public/results/clang-format-PHID-DIFF-ykspmg4mhdehw4stcdos.diff) will force the download.

That or we just rename it `.txt` instead of `.diff`, but that's a bit too hacky for my taste.

**Comment by marco-c** [comment]
There is a contentType option (see https://docs.taskcluster.net/docs/reference/workers/generic-worker/docs/payload).

**Comment by jankeromnes** [comment]
This is now fixed and deployed to production. Thanks @marco-c and @La0!
