### ISSUE TITLE
Filtering clang-format patch generation & display

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#1696]
As we only report some subfolders of *mozilla-unified* with `clang-format` issues, the initial patch generation (full clang-format changes) is too broad.

So we need to:

- [ ] merge [parsepatch chunks support](https://github.com/mozilla/parsepatch/pull/3)
- [ ] parse the full diff with parse patch chunks
- [ ] filter those chunks with in patch + allowed paths
- [ ] build a diff with those chunks
- [x] store the diff as a Taskcluster artifact with `text/plain` content type to display directly in the browser, refs #1690 ([github](https://github.com/mozilla/gecko-dev/commit/11dd9afb588c9733e686d0280a976f8bbf940c8d.diff) example)
- [x] use markdown links in the phabricator comment to avoid long urls

This way we can still have full calng-format analysis & reports in the dashboard, while only reporting sub parts to Phabricator and developers.

**Comment by La0** [comment]
As `./mach clang-format` already filters `clang-format` output on current patch, we only need to work on the display tasks.

Chunk support would be great to have to report fixes in the comment.

**Comment by jankeromnes** [comment]
> Chunk support would be great to have to report fixes in the comment.

Agreed! But then we'll also need to keep in mind the problems we had previously with code snippets inside comments, e.g.

- some fixes were confusing and/or unrelated, because diff hunks are sometimes messed up (e.g. in mass re-indents, when the diff algorithm picks a random `}` as the unchanged line)
- some snippets were just too long to be readable
- it's generally hard to spot the difference between the orignal code a fix snippet (e.g. they're not vertically aligned in Phabricator, so it's hard to guess that a proposed snippet was re-indented).
- etc.
