### ISSUE TITLE
[releaseduty] more notifications per more granular tasks

### ISSUE THREAD

**Issue by MihaiTabara** [mozilla/release-services#1800]
RelMan have been repeatedly asking us if id't be possible to to have a notification in #releaseduty when the balrog rules are ready for signoff. I think this would be beneficial both sides and it's worth doing if we end up improving the current notification system.

**Comment by lundjordan** [comment]
I believe rok and rail were discussing splitting the notification features of shipit, i.e. taskcluster bot, into separate service. This would probably make adding functionality like this issue easier.

**Comment by garbas** [comment]
We already have a working periodic notification service running. eg. notify me this often (you set the policy) on this channels (irc/email/...)

And for regular notification we just use taskcluster notification.

I think we should have a look at the notifications in whole pipeline and not just one place. Since that way we wont over notify people (it would then happen that people would just ignore notifications).

A problem with balrog is that we currently don't have a way of telling if signoff in balrog is done. We would need some way of accessing this from shipit. either moving signoff completely to shipit and do signoff via api or handle this via redirects or something else. either way it should be smooth from the user point of view.

I would love if somebody would lead the way and collect in a google doc all the places where we potentially need notifications (and what kind of notifications).
