### ISSUE TITLE
Make it possible to run projects without a taskcluster client

### ISSUE THREAD

**Issue by marco-c** [mozilla/release-services#786]
It isn't so easy for new contributors to join this project, we should try to make it as easy as possible.
The taskcluster requirement is one of the main pain points in my opinion.

**Comment by marco-c** [comment]
CC @garbas @La0

**Comment by La0** [comment]
The taskcluster client are mostly needed to get the taskcluster secrets (aka cofniguration in our case).
One way to achieve a taskcluster-less dev environment would be to abstract the configuration getter, so that we could load a default static file embedded in the source code (we don't need any credentials for papertrail, heroku or docker on developers computers).

**Comment by marco-c** [comment]
The other, uglier but simpler, option is to create a public Taskcluster client with public secrets.

**Comment by garbas** [comment]
I'm :100: that we should do this, especially if this is a blocker for new contributors. Initially this was not done since it was only "us" and this would require a little bit of work (which nobody usually has :wink:).

Current secrets which i think should stay private that we have in master:
 - CACHE_ACCESS_KEY_ID
 - CACHE_SECRET_ACCESS_KEY
 - DOCKER_PASSWORD
 - CODECOV_ACCESS_TOKEN
 - AUTH_CLIENT_ID
 - AUTH_CLIENT_SECRET
 - DATADOG_API_KEY
 - REPORTERS.api_key
 - PULSE_PASSWORD
 - HOOKS.phabricator_token

I'm positive that not all of this secrets are needed for every project we have.

I think a pragmatic solution (easy to implement) would be that you could provide a secrets file when running `./please` command (without taskcluster client id and access token)? and this file we would share with contributors. This way we would only give them secrets they need and nothing more.

Would that be a possible solution?

**Comment by marco-c** [comment]
It sounds good to me. I think we should also make the basic configuration options for local development that do not need to be secret fully public and put them in the repo. This way new contributors don't always have to ask us for a secrets file (but will ask for a secrets file once they need to test the specific features of the projects that do require secrets).

So maybe `please` can use these basic configuration options and overwrite them if the user provides a secrets file or a Taskcluster secrets path.

**Comment by La0** [comment]
I'm working on this.

The plan is to support loading a local file using  a new `please_cli` option `--local-secret`.
We should have `--local-secret` **XOR** `--taskcluster-secret`.
The `get_secrets` method should behave in the same way, checking file structure and if keys are available or not. This should minimize the impact on projects.

Sample projects secret can then be provided in the repository  for newcomers.

That will not solve the other taskcluster dependencies (index & queue API calls) but should ease the pain for most new devs

**Comment by garbas** [comment]
i would really like to avoid adding more parameters. i'd even remove `--taskcluser-*` parameters if possible. 

I'm -0 on this since i understand it will fix the issue temporarily but complicate in the long run.

I would prefer we look at all the issues we have regarding UX and try simplify ./please command and not adding more clutter.

**Comment by marco-c** [comment]
I guess this is no longer required.
