### ISSUE TITLE
shipit_static_analysis: Problem with an automated review

### ISSUE THREAD

**Issue by padenot** [mozilla/release-services#877]
**MozReview URL:** https://reviewboard.mozilla.org/r/223436/diff/1#index_header

**Problem:**
I see the same defect thrice, on the same line with the same content.

**Comment by jankeromnes** [comment]
Thanks for reporting this issue! This does look like a bug on our side. I'm not aware of any other occurrence of it.

@La0 any ideas why our bot published a review with three times the same defect? Maybe an occasional "concurrent logs" parsing problem?

**Comment by padenot** [comment]
Had this today again: https://bugzilla.mozilla.org/show_bug.cgi?id=1476744#c2

**Comment by La0** [comment]
Here is the [log of the task misbehaving](https://tools.taskcluster.net/groups/RQ3v4gqmR3eNN449AkAB_w/tasks/RQ3v4gqmR3eNN449AkAB_w/runs/0/logs/public%2Flogs%2Flive.log). This is for the diff n°1

There is indeed a strange behaviour, every issue is detected 5 times.

The same thing is [happening for diff n°2](https://tools.taskcluster.net/groups/bMdgD7I6Sa6qLD5_D9Zx-Q/tasks/bMdgD7I6Sa6qLD5_D9Zx-Q/runs/0/logs/public%2Flogs%2Flive.log), fortunately it did not find any publishable issue there.

Same thing on [staging](https://tools.taskcluster.net/groups/EtOQlegvQDiwpSQi6_Dllg/tasks/EtOQlegvQDiwpSQi6_Dllg/runs/0/logs/public%2Flogs%2Flive.log) so the bug is still there.

I tested locally, and the bug is present in the [raw clang-tidy output](https://pastebin.com/raw/enr7tYx1) (each issue is repeated 5 times !)

I can implement a check on our side to avoid publishing the same issue multiple times, but something is broken on mach/clang-tidy (ping @abpostelnicu )

**Comment by abpostelnicu** [comment]
I'm investigating this issue locally, and will come up with a resolution for it shortly.

**Comment by abpostelnicu** [comment]
Looking other this i see that our analysis is based on this review: https://reviewboard.mozilla.org/r/257892/diff/1/

I see there only 3 files modified:

  dom/media/webaudio/AudioListener.h
  dom/media/webaudio/AudioListener.cpp
  dom/media/webaudio/PannerNode.cpp

Looking at the cpp files, we see that AudioListener.h is included in both, so it's normal to have a double error message, since each error message comes from it's own compilation unit. 

Now looking at this [output](https://pastebin.com/raw/enr7tYx1), I see that we are also feeding PannerNode.cpp that is also including  AudioListener.h, so one more error comes from this compilation unit. 

My question is though, why are we calling static-analysis with all of those files?

**Comment by annygakh** [comment]
I'm also having the same issue here https://bugzilla.mozilla.org/show_bug.cgi?id=1472338#c14 (not sure if this is helpful for you, but thought I would comment anyway)

**Comment by jankeromnes** [comment]
Thanks @annygakh, and apologies for the bad experience with our bot.

We clearly need to filter out duplicate defects in our reports. @abpostelnicu, `./mach static-analysis check` doesn't parse `clang-tidy` output, does it? So I guess either:

1. we manage to make `clant-tidy` itself not report duplicates (maybe a more recent `clang-tidy` version won't report duplicates?); or
2. we add another pass to `shipit-static-analysis` *before* publishing comments in order to remove duplicates.

2 looks easier.

**Comment by abpostelnicu** [comment]
@jankeromnes `./mach static-analysis check` parses line by line the output and it adds it to a defects database but it doesn't apply any filters on it.
1. clang-tidy doesn't have the possibility of knowing what it detected or not, since the analysis is done as per compilation unit. The tool doesn't keep and inside database with the reported defects to know what id detected and to filter it out, it just throws the output to the user.
2. We should implement this filter but we should also consider where we want this filter to be applied, at the static-analysis level or in the shipit-static-analysis.

**Comment by La0** [comment]
@abpostelnicu @jankeromnes I'm implementing the filter directly in the bot, pr #1276
