### ISSUE TITLE
`./please check` should run `nix-build` and not `nix-shell`

### ISSUE THREAD

**Issue by garbas** [mozilla/release-services#985]

**Comment by rv404674** [comment]
hey @garbas , can i take up this issue.

**Comment by garbas** [comment]
@rv404674 this would require some [Nix)[https://nixos.org/nix] knowledge? Are you familiar with Nix?

**Comment by rv404674** [comment]
@garbas , nopes. Better to let this one go. :) . I prefer working on sending a notification to IRC, when deployment, via testing/staging/production happens.

**Comment by kevinluvian** [comment]
hi @garbas 

i fixed it in this PR:
https://github.com/mozilla/release-services/pull/1677

I confirmed that when running ./please check codecoverage/backend it runs this command:
```
['nix-build', '/app/nix/default.nix', '-A', 'codecoverage/backend', '-j', '1', '--run', 'pytest tests/; exit']
```

one thing that I am not sure is that should I keep using please_cli.shell.cmd to run the command (https://github.com/kevinluvian/release-services/blob/d1196ea3acecf3f06eecf300bc86b147a6b7d981/lib/please_cli/please_cli/check.py#L60), since the parameter name is nix_shell instead of nix_build
in the end, I decided to reuse please_cli.shell.cmd because it have other configuration such as setting environment variable for taskcluster for now

**Comment by garbas** [comment]
there is `please_cli.build.cmd` (`https://github.com/mozilla/release-services/blob/master/lib/please_cli/please_cli/build.py) which you should use in this case

**Comment by kevinluvian** [comment]
hi @garbas 

from what I understand, it seems like we need to use `please_cli.shell.cmd` due to additional check command to be run

example check command (pytest and linter):
https://github.com/kevinluvian/release-services/blob/d1196ea3acecf3f06eecf300bc86b147a6b7d981/lib/please_cli/please_cli/config.py#L85

this command is called here:
https://github.com/kevinluvian/release-services/blob/d1196ea3acecf3f06eecf300bc86b147a6b7d981/lib/please_cli/please_cli/check.py#L63

the `please_cli.build.cmd` don't have `command` argument
https://github.com/kevinluvian/release-services/blob/d1196ea3acecf3f06eecf300bc86b147a6b7d981/lib/please_cli/please_cli/build.py#L83

while `please_cli.shell.cmd` do
https://github.com/kevinluvian/release-services/blob/d1196ea3acecf3f06eecf300bc86b147a6b7d981/lib/please_cli/please_cli/shell.py#L86

should I add a new arg `command` to `please_cli.build.cmd` ?

**Comment by garbas** [comment]
@kevinluvian oh i forgot to mention to skip those checks, we can actually remove them.

this checks are anyway already part of mkFrontend, mkBackend. so if we run nix-build we will also be running this checks.
